---

- name: install git for checkout of default content
  apt:
    name: git
    state: present

- name: install PHP for admin interface
  apt:
    name: "{{ php_service }}"
    state: present

- name: Enable PHP
  service:
    name: "{{ php_service }}"
    enabled: yes
    state: started

- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "{{ connectbox_default_content_root }}"
    - "{{ connectbox_captive_portal_root }}"

# Copy local client interface files
- name: Copy local connectbox client interface
  when: connectbox_client_repo == ""
  synchronize:
    src: ../html/client/
    dest: "{{ connectbox_default_content_root }}"

# Copy remote client if set
- name: retrieve connectbox-client-repo
  when: connectbox_client_repo != ""
  git:
    repo: "{{ connectbox_client_repo }}"
    dest: /tmp/connectbox_client

- name: Copy external connectbox client interface
  when: connectbox_client_repo != ""
  command: cp -r . "{{ connectbox_default_content_root }}"
  args:
    chdir: /tmp/connectbox_client/{{ connectbox_client_path }}

# Permissions are correctly set in the subsequent task
- name: Copy connectbox admin ui
  synchronize:
    src: ../html/admin/
    dest: "{{ connectbox_admin_root }}"

- name: fix ownership of connectbox_web_root
  file:
    path: "{{ connectbox_web_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Install packages for python virtualenv
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv
    - python-pip
    - virtualenv
  tags:
    - captive_portal

- name: Install packages for captive portal manager process
  pip:
    virtualenv: "{{ connectbox_web_root }}/captive_portal_virtualenv"  # XXX Could do better?
    name: "{{ item }}"
  with_items:
    - flask
    - ua-parser
    - gunicorn
    - requests
  tags:
    - captive_portal

# Copy client interface files
- name: Copy connectbox client interface
  synchronize:
    src: ../html/captive_portal/
    dest: "{{ connectbox_captive_portal_root }}"
  tags:
    - captive_portal
  notify:
    - Restart gunicorn

- name: Copy gunicorn tempfiles definition
  template:
    src: etc_tmpfiles.d_gunicorn.conf.j2
    dest: /etc/tmpfiles.d/gunicorn.conf
  tags:
    - captive_portal

- name: Copy gunicorn systemd unit file
  template:
    src: etc_systemd_system_gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  tags:
    - captive_portal
  notify: Restart gunicorn

- name: Enable gunicorn service
  service:
    name: gunicorn
    enabled: yes
    #state: started
  tags:
    - captive_portal
